project:
  name: quickstart-amazon-eks
  owner: quickstart-eng@amazon.com
  regions:
  - ap-east-1
  - ap-northeast-1
  - ap-south-1
  - ap-southeast-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - me-south-1
  - sa-east-1
  - us-east-1
  - us-east-2
  template: templates/amazon-eks-master.template.yaml
  parameters:
    RemoteAccessCIDR: 10.0.0.0/16
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    #ProvisionBastionHost: Disabled
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
tests:
  with-hybrid:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ProvisionBastionHost: Enabled
      ClusterAutoScaler: Disabled
      ManagedNodeGroup: 'yes'
      ManagedNodeGroupAMIType: AL2_x86_64
      MangedNodeGroupLabel: TestMNG
    regions:
    - us-west-2


